### ISSUE TITLE
it did not work

### ISSUE THREAD

**Issue by luoyue123321** [penumbram/DNSChanger#1]
▿ some : 4 elements
    ▿ 0 : 2 elements
      - key : NSAppleScriptErrorMessage
      - value : The administrator user name or password was incorrect.
    ▿ 1 : 2 elements
      - key : NSAppleScriptErrorBriefMessage
      - value : The administrator user name or password was incorrect.
    ▿ 2 : 2 elements
      - key : NSAppleScriptErrorRange
      - value : NSRange: {0, 113}
    ▿ 3 : 2 elements
      - key : NSAppleScriptErrorAppName
      - value : DNSChanger

**Comment by penumbram-zz** [comment]
Hi luoyue123321,

This repository has no proper documentation, sorry for the inconvenience. In ViewController.swift, you have to change the variables "username" and "password" to your credentials and try again. Let me know if you have further trouble.

**Comment by penumbram-zz** [comment]
Hi luoyue123321,

Could you get it to work? I'm here to help further if you need anything.
